### ISSUE TITLE
Feature request: GraphQL support

### ISSUE THREAD

**Issue by Kani999** [netbox-community/pynetbox#405]
Hello,

is there a planned GraphQL queries implementation since Netbox 3.0 support this feature? 
GraphQL is not part of '/api' endpoint but it has own 'graphql/' path.

Is it possible to implement the GraphQL queries into the pynetbox? 

Thank you

**Comment by zachmoody** [comment]
:wave:  I hadn't really planned on including it. Mostly because there's plenty of well-support GQL libraries out there already, and I'm not that interested in making another one. I don't really think the value pynetbox adds to NetBox's REST API is there with something as expressive as graphql, but maybe I'm just not seeing it.

Happy to leave this issue open for a while to see if others feel differently.

**Comment by ryanmerolle** [comment]
I'd actually like to bring this back up.  I was more in the same mind as @zachmoody 

Recently I came across [nautobot ansible variable management at scale](https://blog.networktocode.com/post/nautobot-ansible-variable-management-at-scale)

I would frankly want to implement this same sort of feature in netbox ansible modules.  We have an issue already for this 

- netbox-community/ansible_modules#566

**Comment by arthanson** [comment]
IMHO GraphQL support is outside the scope of this project - this is specifically for RestAPI and GraphQL would be completely separate.  I'd suggest creating a separate library.
