### ISSUE TITLE
VirtualChassis DCIM use of display_name

### ISSUE THREAD

**Issue by danwalkeruk** [netbox-community/pynetbox#437]
When trying to do `str(foo)` where foo represents a Virtual Chassis, an exception is thrown:

```
Traceback (most recent call last):
  File "script.py", line X, in <module>
    if str(foo):
  File "/usr/local/lib/python3.6/site-packages/pynetbox/models/dcim.py", line 156, in __str__
    return self.master.display_name
  File "/usr/local/lib/python3.6/site-packages/pynetbox/core/response.py", line 298, in __getattr__
    raise AttributeError('object has no attribute "{}"'.format(k))
AttributeError: object has no attribute "display_name
```

I believe `display_name` has been deprecated, and so this should instead be either `.name` or `.display`.

**Comment by markkuleinio** [comment]
`display_name` is not deprecated but wholly replaced by `display` on NetBox 2.10 or so (see NetBox release notes for exact release), so the behaviour depends on NetBox version.

I will later write a PR to add support for `display`. Meanwhile as a workaround, consider using the specific attribute instead of the generic string representation of the object, for example using `foo.name` (if present in VC) instead of `str(foo)`.
