### ISSUE TITLE
Updating assigned_object_id does not refresh assigned_object in instance

### ISSUE THREAD

**Issue by klausmark** [netbox-community/pynetbox#496]
Updating assigned_object_id does not refresh assigned_object in instance
```python
>>> type(ip)
<class 'pynetbox.models.ipam.IpAddresses'>
>>> ip.update({"assigned_object_id": 10})
True
>>> ip.assigned_object_id
10
>>> ip.assigned_object.id
5359
````

**Comment by markkuleinio** [comment]
If I'm not mistaken, it has always been so that if you update some of the objects properties and save it, `pynetbox` does not make extra calls to NetBox API automatically to update the full object (there is no other way to know all the field contents).

If you need the object to be fully updated, you need to call `ip.full_details()` after partially updating the object: that forces execution of extra NetBox API calls (one or more) to populate all the details.

**Comment by klausmark** [comment]
Thanks for the explanation, and it makes sense, to make as few API calls as possible. But the update leaves the instance in i wrong state.
